config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  get '/about', to: 'pages#about'

  get 'lesson/:title', to: 'lessons#show', as: 'lesson'
  delete 'lesson/:id', to: 'lessons#destroy'
  patch 'lesson/:id', to: 'lessons#update'
  resources :lessons, except: [:show, :destroy, :update]
  resources :steps, except: [:index]

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :steps, dependent: :destroy
  validates :title, presence: true
  
  def last_step
    self.steps.order(:step_number).last
  end
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :lesson
  validates :title, presence: true
  validates :lesson_id, presence: true
  validates :step_number, presence: true
  validates :instruction, presence: true
  
  def next
    self.lesson.steps.where("step_number > ?", self.step_number).first
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  include ApplicationHelper
  before_action :require_admin, except: [:index, :show]
  before_action :set_lesson, only: [:edit, :update, :destroy]

  def index
    @lessons = Lesson.all
  end

  def new
    @lesson = Lesson.new
  end

  def edit
  end

  def update
    if @lesson.update(lesson_params)
      flash[:success] = "Lesson was successfully updated"
      redirect_to lesson_path(@lesson.title)
    else
      render 'edit'
    end
  end

  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      flash[:success] = "Lesson was successfully created"
      redirect_to lesson_path(@lesson.title)
    else
      render 'new'
    end
  end

  def show
    title = params[:title].tr('-', ' ')
    @lesson = Lesson.find_by_title(title)
    @step = @lesson.steps.order(:step_number).first
  end

  def destroy
    @lesson.destroy
    flash[:danger] = "Lesson was successfully deleted"
    redirect_to lessons_path
  end

  private

  def lesson_params
    params.require(:lesson).permit(:title, :current_step)
  end

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @lessons = Lesson.all
  end
  
  def about
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  include ApplicationHelper
  before_action :require_admin, except: [:show]
  before_action :set_step, only: [:edit, :update, :destroy, :show]

  def new
    @step = Step.new
  end

  def edit
  end

  def update
    if @step.update(step_params)
      flash[:success] = "Step was successfully updated"
      redirect_to lesson_path(@step.lesson.title)
    else
      render 'edit'
    end
  end

  def create
    @step = Step.new(step_params)
    if @step.save
      flash[:success] = "Step was successfully created"
      redirect_to lesson_path(@step.lesson.title)
    else
      render 'new'
    end
  end

  def show
    respond_to do |format|
      format.js { render :show_step }
    end
  end

  def destroy
    @step.destroy
    flash[:danger] = "Step was successfully deleted"
    redirect_to lesson_path(@step.lesson.title)
  end

  private

  def step_params
    params.require(:step).permit(:title, :lesson_id, :step_number, :html,
                                 :css, :javascript, :instruction)
  end

  def set_step
    @step = Step.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def require_admin
    current_user.nil? ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end

  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
    
  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true,)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_spacing: true
    }
    return Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/views/layouts/_messages.html.erb
<div class="col-xs-3">
  <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}"%>' role ="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<section class="navigation">
  <div class="nav-toggle-container">
    <a id="nav-toggle"><span></span></a>
  </div>
  <%= link_to "Web Dev Nuggets", root_path, class: "navbar-brand" %>
  <div class="link-container">
    <ul>
      <li>
        <%= link_to '/about' do %>
        <i class="fa fa-exclamation-circle"></i> About
        <% end %>
      </li>
      <li>
        <%= link_to lessons_path do %>
        <i class="fa fa-graduation-cap"></i> Go to Lessons
        <% end %>
      </li>
    </ul>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Web Dev Nuggets</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
</head>

<body>
  
  <!--Render NAV -->
  <%= render 'layouts/navigation' %>
  <!-- end Render NAV -->
  
  <!--content-->
  <div class="container-fluid site-body">
    <div class="row">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </div>
  
  <div class="container-fluid">
    <%= yield :about %>
    <%= yield :index %>
    <%= yield :editor %>
  </div>
  <!--end content-->
  
</body>

</html>

app/views/lessons/_form.html.erb
<%= render 'shared/errors', obj: @lesson %>
<div class="col-md-6">
  <%= form_for(@lesson) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/lessons/_index.html.erb
<div class="container">
  
  <div class="row">
    <div class="header">
      <h1>Lessons
        <small>more coming soon!</small>
      </h1>
    </div>
  </div>
  
  <% @lessons.reverse.each do |lesson| %>
    <div class="row">
      <div class="cards">
        <h3>
          <% title = lesson.title.tr(' ', '-') %>
          <%= link_to lesson.title, lesson_path(title) %>
        </h3>
        <% if current_user.try(:admin?) %>
          <%= link_to "edit", edit_lesson_path(lesson), class: "btn btn-xs btn-primary" %>
          <%= link_to "delete", lesson_path(lesson), method: :delete,
                                data: { confirm: "Are you sure you want to delete?" },
                                class: "btn btn-xs btn-danger" %>
        <% end %>
      </div>
      <% unless lesson.last_step.nil? %>
        <%= content_tag "iframe", class: "lesson-preview", id: lesson.title.delete(' '),
                                  data: {title: lesson.title.delete(' '),
                                         html: lesson.last_step.html,
                                         css: lesson.last_step.css,
                                         javascript: lesson.last_step.javascript} do %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/lessons/edit.html.erb
<%= render 'form' %>

app/views/lessons/index.html.erb
<% content_for :index do %>
  <%= render "index" %>
<% end %>

app/views/lessons/new.html.erb
<%= render 'form' %>

app/views/lessons/show.html.erb
<% content_for :editor do %>
  <div class="container-editor">
    <div class="col-md-3 scrollable" id="cool-scrollbar">
      <h2><%= @lesson.title %></h2>
      <% if current_user.try(:admin?) %>
        <%= link_to "New Step", new_step_path(:lesson_id => @lesson.id)%>
      <% end %>
      <div class='step-dropdown'>
        <div class='step-preview'>
          <% unless @lesson.last_step.nil? %>
            <%= @lesson.steps.order(:step_number).first.title %>
          <% end %>
        </div>
        <% @lesson.steps.order(:step_number).each do |step| %>
          <%= content_tag "div", class: "step-input", id: step.title.delete(' ') do %>
            <%= link_to "#{step.title}", step_path(step), remote: true %>
          <% end %>
        <% end %>
      </div>
      <div id="step-results">
        <% unless @lesson.last_step.nil? %>
          <%= render "/steps/show" %>
        <% end %>
      </div>
    </div>
  
    <div class="col-md-9">
      <%= render '/shared/editor' %>
    </div>
  </div>
<% end %>

app/views/pages/about.html.erb
<% content_for :about do %>
  <div class="container-fluid">
    <div class="container about-container">
      <p> This website is meant for anyone who has learnt the basics of html, 
          css, and javascript and are looking for ways to improve upon their skills and 
          build practical features to implement in their own websites.</p>
          Features of this website
      <ul>
        <li>
          Live preview of html, css, and javascript compiled into an iframe
        </li>
        <li>
          Resizable modal to see a preview at all resolutions
        </li>
        <li>
          Steps cycle through with ajax, not interrupting your code
        </li>
        <li>
          Solution button to input code up to the end of the current step
        </li>
        <li>
          Live preview for the final product under each lesson link
        </li>
      </ul>
      <p>
        This website was created by <a href="https://github.com/Exellin">Shawn Carnegie</a> 
        and <a href="https://github.com/wade0727">Matt</a>.
      </p>
      <p>
        This website was made with Ruby on Rails and is open source.  The github repository 
        can be found <a href="https://github.com/RoR-Strangers/webdevnuggets">here</a>.
      </p>
    </div>
  </div>
<% end %>

app/views/pages/home.html.erb
<header class="business-header">
  <div class="container">
    <div class="col-lg-12">
      <h1 class="tagline">Web Dev Nuggets</h1>
      <p class="lead">Come develop your <code>&lt;/code&gt;</code> skills with our FREE interactive lessons.</p>
    </div>    
  </div>
</header>

<% content_for :index do %>
  <%= render "/lessons/index" %>
<% end %>
    

app/views/shared/_editor.html.erb
<div class="col-xs-12 text-center">
  <button class="btn btn-primary btn-lg" id="loadModal" 
          data-toggle="modal" data-target="#myModal">
  Open in Resizable Window
  </button>
  <button class="btn btn-warning btn-lg" id="solution">
    Show Solution
  </button>
</div>

<div class="row editor-row">
  <div class="col-md-4">
    <span class="label label-default col-lg-12 fancy-bar">HTML</span>
    <div class="editor" id="html"></div>
  </div>
  <div class="col-md-4">
    <span class="label label-default col-lg-12 fancy-bar">CSS</span>
    <div class="editor" id="css"></div>
  </div>
  <div class="col-md-4">
    <span class="label label-default col-lg-12 fancy-bar">Javascript</span>
    <div class="editor" id="javascript"></div>
  </div>
</div>

<div class="row view-row">
  <div class="col-md-12">
    <iframe id="targetCode"></iframe> 
  </div>
</div>

<div class="modal fade" id="myModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal"><span>&times;</span></button>
        <h4 class="modal-title"> Resizable Preview</h4>
        <button class="screen_selector" data-width="400px" data-height="500px">
          Switch to Mobile
        </button>
        <button class="screen_selector" data-width="1280px" data-height="720px">
          Switch to Desktop
        </button>
      </div>
      <div class="modal-body">
        <div id="resizable">
           <iframe id="modalIframe"></iframe> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h2 class="panel-title">
        <%= pluralize(obj.errors.count, "error") %>
        prohibited this article from being saved:
      </h2>
      <div class="panel-body">
        <u1>
          <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </u1>
      </div>
    </div>
  </div>
<% end %>

app/views/steps/_form.html.erb
<div class="container">
  <%= render 'shared/errors', obj: @step %>
  <%= form_for(@step) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.hidden_field(:lesson_id, :value => params[:lesson_id]) %>
    </div>
    <div class="form-group">
      <%= f.label :step_number %>
      <%= f.number_field :step_number, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :instruction %>
      <%= f.text_area :instruction, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :html %>
      <%= f.text_area :html, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :css %>
      <%= f.text_area :css, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :javascript %>
      <%= f.text_area :javascript, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/steps/_show.html.erb
<%= markdown(@step.instruction) %>
<% unless @step.next.nil? %>
  <%= link_to "Next Step", step_path(@step.next), remote: true,
                           class: "btn btn-xs btn-primary" %>
<% end %>
<%= content_tag "div", id: "insert", data: {html: @step.html,
                                            css: @step.css,
                                            javascript: @step.javascript,
                                            title: @step.title} do %>
<% end %>
<% if !current_user.nil? and current_user.admin? %>
  <%= link_to "edit", edit_step_path(@step, :lesson_id => @step.lesson_id), 
                      class: "btn btn-xs btn-primary" %>
  <%= link_to "delete", step_path(@step), method: :delete, 
                        data: { confirm: "Are you sure you want to delete?" },
                        class: "btn btn-xs btn-danger" %>
<% end %>

app/views/steps/edit.html.erb
<%= render 'form' %>

app/views/steps/new.html.erb
<%= render 'form' %>

app/views/steps/show.html.erb
<h3><%= @step.title %></h3>
<%= @step.instruction %>

app/views/steps/show_step.js.erb
$("#step-results").html("<%=escape_javascript(render 'show')%>");

var title = $('#insert').data('title'),
    dropdown_target = title.replace(/\s/g, ''),
    step = document.querySelector("[id=" + dropdown_target + "]");
    
$(".step-input").removeClass("active");
step.classList.add("active");
$('.step-preview').text(title);